Is91 api items
UB-ES-2020-F/UBEats pull request #120
Opened 2020-11-17 19:20 UTC by oriolOrnaque

api item "bugs": 

- tests-ddbb dependency
- paths for delete/put use now the path parameter for item_id instead of the body

2020-11-21 12:54 UTC, hectorAlarcon requested changes
Good job! Evertyhing seems to work fine. But there are some questions/issues : 
 1. Why the URL attr has a 200 char limit? 
2.  URL may be a null value. That restriction makes no sense.
3. Test must help devs understand how an endpoints works. If the value of each attr is a combination of random keys its hardly understandable. All test should simulate a real case. Please check it out

2020-11-25 02:43 UTC, Rbb93 approved these changes

2020-11-29 04:00 UTC, Rbb93 requested changes
Los tests funcionan todos si la base de datos está completa segun el script sql, pero en cambio si la dejo vacia, fallan varios de las api items y users, por tanto hay dependencia de los datos pre existentes. Hay que corregir eso. Resto OK

2020-11-30 01:10 UTC, Rbb93 approved these changes

2020-11-30 06:41 UTC, hectorAlarcon approved these changes

2020-11-30 06:42 UTC, merged