#153
UB-ES-2020-F/UBEats pull request #180
Opened 2020-12-12 11:50 UTC by Samuroldan

DONE

2020-12-12 16:11 UTC, aldakata requested changes
Me sale vacio, sin restaurantes. No puedo testearlo así, tengo que hacer algo especial?

![imagen](https://user-images.githubusercontent.com/28759993/101988913-0d8fec00-3c9d-11eb-9445-5caa010bc692.png)

2020-12-12 16:23 UTC, Samuroldan commented
De esto queria yo hablar contigo, si es posible quedar mañana y te comento esto, me vendria de lujo porque soy incapaz de mostrar los restaurantes. Gracias.

2020-12-13 11:11 UTC, Samuroldan commented
All images from database, and all restaurant images link to restaurant page.

2020-12-13 16:21 UTC, aldakata approved these changes
Accepted. Good work.

2020-12-13 18:59 UTC, hectorAlarcon approved these changes
Good work but be careful on submitting local code.

2020-12-14 21:58 UTC, merged